### DISCUSSION TITLE
How to end linked messages without whitespace

### DISCUSSION THREAD

**Discussion by MrTanoshii** [intlify/vue-i18n#1008] [Q&A]
### Problem
I've tested my code using js object and yaml

My issue is I have code that looks like this:
```yml
en_us:
  settings:
    save_wipe_confirmation_text: Enable Data Wipe
    save_wipe_placeholder: Enter '@:settings.save_wipe_confirmation_text'
```

Expected output: `Enter 'Enable Data Wipe'`
Actual output: `Enter`

### "Solutions"

1. This can be "fixed" by adding a space inbetween `...'@:settings.save_wipe_confirmation_text '` but of course, then the output is `Enter 'Enable Data Wipe '` (note the extra whitespace)
2. I could handle it as interpolation but I would prefer doing all this in the object itself as vue-i18n has linked messages

### Question
Is there a way to end the linked message without adding the whitespace?

**Comment by MrTanoshii** [comment]
I ended up using a named interpolation instead of a linked message

```yaml
settings:
  save_wipe_confirmation_text: Enable Data Wipe
  save_wipe_feedback:
    Enter '{confirmation_text}' (case sensitive) to unlock permanent deletion of
    ALL data.
```

```vue
{{
  $t("settings.save_wipe_feedback", {
    confirmation_text: $t("settings.save_wipe_confirmation_text"),
  })
}}
```
