### DISCUSSION TITLE
How to use pluralization inside a linked message

### DISCUSSION THREAD

**Discussion by cuongvuong-phoenix** [intlify/vue-i18n#587] [Q&A] [answered]
Assume I have some messages as follows:

```yaml
# en.yaml
point: Point | Points
my-points: "My @.lower:{'point'}"
```

When using `my-points` key, ***vue-i18n*** converts it as `My point`. But as you can see from the key name, it should be `My points` instead.
The official documentation doesn't mention a way to specify pluralization (like when using `$t('point', 0)`) for linked message. So how can I achieve this fuctionality? Does ***vue-i18n*** support it or not?
