### ISSUE TITLE
petite-vue-i18n does not support translation in this format

### ISSUE THREAD

**Issue by maxfrees** [intlify/vue-i18n#1962]
### Reporting a bug?

```
baseTable:
  item: i
  total: to
  strip: str
  filterColumn: filter column
```

petite-vue-i18n does not support translation in this format

https://stackblitz.com/edit/vitejs-vite-xzgccz

### Expected behavior

```
baseTable:
  item: i
  total: to
  strip: str
  filterColumn: filter column
```

petite-vue-i18n does not support translation in this format

### Reproduction

```
baseTable:
  item: i
  total: to
  strip: str
  filterColumn: filter column
```

petite-vue-i18n does not support translation in this format

### System Info

```shell
*
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/vue-i18n/blob/master/.github/CONTRIBUTING.md)
- [X] Read the [Documentation](https://vue-i18n.intlify.dev/)
- [X] Check that there isn't [already an issue](https://github.com/intlify/vue-i18n/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussions](https://github.com/intlify/vue-i18n/discussions)
